### ISSUE TITLE
Application unable to read external properties file after upgrading WKO from 3.2.0 to 4.0.0

### ISSUE THREAD

**Issue by jkramplify** [oracle/weblogic-kubernetes-operator#4061]
I encountered issues when upgrading from 3.2.0 to 4.0.0. Some of our applications suddenly unable to read an external environment.properties  file located at DOMAIN_HOME/wlsdeploy/environment.properties. 

The way our applications are reading this file is `<beans:value>file:wlsdeploy/environment.properties</beans:value>`

Nothing changed in the application side. The only changes were upgrading  WKO to 4.0.0 and using oracle.weblogic/v9 domain schema.

**Comment by rjeberhard** [comment]
Are you using 4.0.0 or the latest, 4.0.5?

**Comment by jkramplify** [comment]
> Are you using 4.0.0 or the latest, 4.0.5?

4.0.0 But I can upgrade to 4.0.5 if you would recommend that.

**Comment by rjeberhard** [comment]
None of the fixes in 4.0.1 through 4.0.5 seem immediately relevant to the problem you are facing (https://github.com/oracle/weblogic-kubernetes-operator/releases); however, I'd still recommend upgrading to 4.0.5 for two related reasons: 1) It's possible that 4.0.5 will resolve your problem because your issue was a side-effect of one of the issues that was fixed and so it would be a shame to waste time diagnosing such a problem, and 2) If we do need to fix a bug and release a fix then this would be a 4.0.6 release. We don't have a process for delivering patches similar to how this is done for WebLogic.

**Comment by jkramplify** [comment]
Hi @rjeberhard still having the same issue with 4.0.5. So for now we will not update our wko. And in the meantime I will try to find out at which version after 3.2.3 the issue occurs.

**Comment by robertpatrick** [comment]
@jkramplify Please see https://oracle.github.io/weblogic-deploy-tooling/concepts/archive/#wlsdeploycustom.  Dropping a random file in a random location in the WDT Archive is not supported (and never has been--even if it was previously working).
